version: '3.8'

services:
  app:
    build: .
    container_name: ton-storage-s3
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "3000:3000"
      - "14321:14321/udp"
    environment:
      - SERVER_PORT=:8080
      - DB_URL=postgres://user:password@postgres:5432/ton_storage?sslmode=disable
      - TON_CONFIG_URL=https://ton.org/global.config.json
      
      - INTERNAL_DB_PATH=/root/var/ton-db
      - DOWNLOADS_PATH=/root/var/downloads
      
      - REPLICATOR_WORKERS=5
      - AUDITOR_WORKERS=3
      - DEFAULT_REPLICAS=3
      
      - WALLET_SEED=${WALLET_SEED}
    volumes:
      - ton_db_data:/root/var/ton-db
      - downloads_data:/root/var/downloads
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: ton-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ton_storage
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pg_data:
  ton_db_data:
  downloads_data: