services:
  app:
    build: .
    container_name: ton-storage-s3
    restart: unless-stopped
    
    network_mode: "host"
    

    environment:
      - SERVER_PORT=:8080
      
      - DB_URL=postgres://user:password@127.0.0.1:5432/ton_storage?sslmode=disable
      
      - TON_CONFIG_URL=https://ton.org/global.config.json
      - INTERNAL_DB_PATH=/root/var/ton-db
      - DOWNLOADS_PATH=/root/var/downloads
      
      - REPLICATOR_WORKERS=5
      - AUDITOR_WORKERS=3
      - DEFAULT_REPLICAS=3
      
      - WALLET_SEED=${WALLET_SEED}
      
      - EXTERNAL_IP=${EXTERNAL_IP}
      
    volumes:
      - ton_db_data:/root/var/ton-db
      - downloads_data:/root/var/downloads
    depends_on:
      - postgres

  postgres:
    image: public.ecr.aws/docker/library/postgres:15-alpine
    container_name: ton-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ton_storage
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data:
  ton_db_data:
  downloads_data:
